const fs = require('fs');

const path = 'artifacts/agroguard/src/context/language.tsx';
let content = fs.readFileSync(path, 'utf8');

const missingEn = `
    "My Farm": "My Farm",
    "Overview": "Overview",
    "My Devices": "My Devices",
    "Buy Hardware": "Buy Hardware",
    "My Orders": "My Orders",
    "Crop Diagnosis": "Crop Diagnosis",
    "Seed Quality": "Seed Quality",
    "Disease Forecast": "Disease Forecast",
    "Analysis History": "Analysis History",
    "Farming Guides": "Farming Guides",
    "AI Assistant": "AI Assistant",
    "Command Center": "Command Center",
    "Knowledge Centre": "Knowledge Centre",
    "Field Officer": "Field Officer",
    "My Tasks": "My Tasks",
    "Farmers Directory": "Farmers Directory",
    "Manage Knowledge": "Manage Knowledge",
    "Platform": "Platform",
    "Dashboard": "Dashboard",
    "Farmers": "Farmers",
    "Deployments": "Deployments",
    "All Devices": "All Devices",
    "Hardware Inventory": "Hardware Inventory",
    "Maintenance Logs": "Maintenance Logs",
    "Alerts": "Alerts",
    "Analytics": "Analytics",
    "Administration": "Administration",
    "Staff": "Staff",
    "Achievements": "Achievements",
    "System Audit Logs": "System Audit Logs",
    "Admin Actions": "Admin Actions",
`;

const missingHa = `
    "My Farm": "Gona ta",
    "Overview": "Dubawa",
    "My Devices": "Na'urorina",
    "Buy Hardware": "Sayi Na'ura",
    "My Orders": "Odojina",
    "Crop Diagnosis": "Binciken Amfanin Gona",
    "Seed Quality": "Ingancin Iri",
    "Disease Forecast": "Hasashen Cuta",
    "Analysis History": "Tarihin Bincike",
    "Farming Guides": "Jagoran Noma",
    "AI Assistant": "Mataimakin AI",
    "Command Center": "Cibiyar Kula",
    "Knowledge Centre": "Cibiyar Ilimi",
    "Field Officer": "Jami'in Fage",
    "My Tasks": "Ayyukana",
    "Farmers Directory": "Kundin Manoma",
    "Manage Knowledge": "Sarrafa Ilimi",
    "Platform": "Dandalin",
    "Dashboard": "Allon Kula",
    "Farmers": "Manoma",
    "Deployments": "Turawa",
    "All Devices": "Dukkan Na'urori",
    "Hardware Inventory": "Kayan Na'ura",
    "Maintenance Logs": "Rikodin Gyara",
    "Alerts": "Fadakarwa",
    "Analytics": "Kididdiga",
    "Administration": "Gudanarwa",
    "Staff": "Ma'aikata",
    "Achievements": "Nasara",
    "System Audit Logs": "Rikodin Ayyukan Tsarin",
    "Admin Actions": "Ayyukan Gudanarwa",
`;

const missingFr = `
    "My Farm": "Ma Ferme",
    "Overview": "Aperçu",
    "My Devices": "Mes Appareils",
    "Buy Hardware": "Acheter du Matériel",
    "My Orders": "Mes Commandes",
    "Crop Diagnosis": "Diagnostic des Cultures",
    "Seed Quality": "Qualité des Graines",
    "Disease Forecast": "Prévision des Maladies",
    "Analysis History": "Historique des Analyses",
    "Farming Guides": "Guides Agricoles",
    "AI Assistant": "Assistant IA",
    "Command Center": "Centre de Commande",
    "Knowledge Centre": "Centre de Connaissances",
    "Field Officer": "Agent de Terrain",
    "My Tasks": "Mes Tâches",
    "Farmers Directory": "Annuaire des Agriculteurs",
    "Manage Knowledge": "Gérer les Connaissances",
    "Platform": "Plateforme",
    "Dashboard": "Tableau de Bord",
    "Farmers": "Agriculteurs",
    "Deployments": "Déploiements",
    "All Devices": "Tous les Appareils",
    "Hardware Inventory": "Inventaire du Matériel",
    "Maintenance Logs": "Journaux de Maintenance",
    "Alerts": "Alertes",
    "Analytics": "Analyses",
    "Administration": "Administration",
    "Staff": "Personnel",
    "Achievements": "Réalisations",
    "System Audit Logs": "Journaux d'Audit",
    "Admin Actions": "Actions Administratives",
`;

const missingAr = `
    "My Farm": "مزرعتي",
    "Overview": "نظرة عامة",
    "My Devices": "أجهزتي",
    "Buy Hardware": "شراء الأجهزة",
    "My Orders": "طلباتي",
    "Crop Diagnosis": "تشخيص المحاصيل",
    "Seed Quality": "جودة البذور",
    "Disease Forecast": "توقع الأمراض",
    "Analysis History": "تاريخ التحليل",
    "Farming Guides": "أدلة الزراعة",
    "AI Assistant": "المساعد الذكي",
    "Command Center": "مركز القيادة",
    "Knowledge Centre": "مركز المعرفة",
    "Field Officer": "موظف ميداني",
    "My Tasks": "مهامي",
    "Farmers Directory": "دليل المزارعين",
    "Manage Knowledge": "إدارة المعرفة",
    "Platform": "المنصة",
    "Dashboard": "لوحة القيادة",
    "Farmers": "المزارعون",
    "Deployments": "الانتشارات",
    "All Devices": "جميع الأجهزة",
    "Hardware Inventory": "جرد الأجهزة",
    "Maintenance Logs": "سجلات الصيانة",
    "Alerts": "تنبيهات",
    "Analytics": "التحليلات",
    "Administration": "الإدارة",
    "Staff": "الموظفون",
    "Achievements": "الإنجازات",
    "System Audit Logs": "سجلات النظام",
    "Admin Actions": "إجراءات الإدارة",
`;

const missingSw = `
    "My Farm": "Shamba Langu",
    "Overview": "Muhtasari",
    "My Devices": "Vifaa Vyangu",
    "Buy Hardware": "Nunua Vifaa",
    "My Orders": "Agizo Langu",
    "Crop Diagnosis": "Utambuzi wa Mazao",
    "Seed Quality": "Ubora wa Mbegu",
    "Disease Forecast": "Utabiri wa Magonjwa",
    "Analysis History": "Historia ya Uchambuzi",
    "Farming Guides": "Miongozo ya Kilimo",
    "AI Assistant": "Msaidizi wa AI",
    "Command Center": "Kituo cha Amri",
    "Knowledge Centre": "Kituo cha Maarifa",
    "Field Officer": "Afisa wa Nyanjani",
    "My Tasks": "Kazi Zangu",
    "Farmers Directory": "Orodha ya Wakulima",
    "Manage Knowledge": "Simamia Maarifa",
    "Platform": "Jukwaa",
    "Dashboard": "Dashibodi",
    "Farmers": "Wakulima",
    "Deployments": "Kusambazwa",
    "All Devices": "Vifaa Vyote",
    "Hardware Inventory": "Orodha ya Vifaa",
    "Maintenance Logs": "Kumbukumbu za Matengenezo",
    "Alerts": "Tahadhari",
    "Analytics": "Uchambuzi",
    "Administration": "Utawala",
    "Staff": "Wafanyakazi",
    "Achievements": "Mafanikio",
    "System Audit Logs": "Kumbukumbu za Ukaguzi wa Mfumo",
    "Admin Actions": "Vitendo vya Msimamizi",
`;

// Insert the missing parts before the closing brace of each language section
content = content.replace(/(en: \{[\s\S]*?)("no-data"[^\n]*\n)(  \},)/, "$1$2" + missingEn + "$3");
content = content.replace(/(ha: \{[\s\S]*?)("no-data"[^\n]*\n)(  \},)/, "$1$2" + missingHa + "$3");
content = content.replace(/(fr: \{[\s\S]*?)("no-data"[^\n]*\n)(  \},)/, "$1$2" + missingFr + "$3");
content = content.replace(/(ar: \{[\s\S]*?)("no-data"[^\n]*\n)(  \},)/, "$1$2" + missingAr + "$3");
content = content.replace(/(sw: \{[\s\S]*?)("no-data"[^\n]*\n)(  \},)/, "$1$2" + missingSw + "$3");

// Also fix useEffect missing dependency
content = content.replace(
  /useEffect\(\(\) => \{\n    document\.documentElement\.lang = language;\n    document\.documentElement\.dir = language === "ar" \? "rtl" : "ltr";\n  \}, \[\]\);/,
  'useEffect(() => {\n    document.documentElement.lang = language;\n    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";\n  }, [language]);'
);

fs.writeFileSync(path, content, 'utf8');
console.log('Language dictionary updated successfully');
