/**
 * Language Context — Lightweight i18n for AgroGuard.
 * Supports: English (en), Hausa (ha), French (fr), Arabic (ar), Swahili (sw).
 * Falls back to English if a key is missing for the chosen language.
 */
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type SupportedLanguage = "en" | "ha" | "fr" | "ar" | "sw" | "yo" | "ig" | "zu" | "am" | "so";

export const LANGUAGE_OPTIONS: { code: SupportedLanguage; label: string; nativeLabel: string }[] = [
  { code: "en", label: "English", nativeLabel: "English" },
  { code: "ha", label: "Hausa", nativeLabel: "Hausa" },
  { code: "yo", label: "Yoruba", nativeLabel: "Yorùbá" },
  { code: "ig", label: "Igbo", nativeLabel: "Igbo" },
  { code: "fr", label: "French", nativeLabel: "Français" },
  { code: "ar", label: "Arabic", nativeLabel: "العربية" },
  { code: "sw", label: "Swahili", nativeLabel: "Kiswahili" },
  { code: "zu", label: "Zulu", nativeLabel: "isiZulu" },
  { code: "am", label: "Amharic", nativeLabel: "አማርኛ" },
  { code: "so", label: "Somali", nativeLabel: "Soomaali" },
];

type TranslationDictionary = Record<string, string>;
type Translations = Partial<Record<SupportedLanguage, TranslationDictionary>>;

const translations: Translations = {
  en: {
    dashboard: "Dashboard",
    farmers: "Farmers",
    devices: "Devices",
    "crop-diagnosis": "Crop Diagnosis",
    "ai-assistant": "AI Assistant",
    alerts: "Alerts",
    analytics: "Analytics",
    settings: "Settings",
    logout: "Logout",
    "analysis-history": "Analysis History",
    "farming-guide": "Farming Guide",
    "admin-audit-logs": "Audit Logs",
    // Disease Result Card
    "diagnosis.disease": "Disease",
    "diagnosis.confidence": "Confidence",
    "diagnosis.severity": "Severity",
    "diagnosis.recommended-action": "Recommended Action",
    "diagnosis.prevention": "Prevention Tips",
    "diagnosis.recovery": "Estimated Recovery",
    "diagnosis.severity.low": "Low",
    "diagnosis.severity.medium": "Medium",
    "diagnosis.severity.high": "High",
    "diagnosis.severity.critical": "Critical",
    // Feedback
    "feedback.title": "Did this recommendation solve your problem?",
    "feedback.yes": "Yes",
    "feedback.no": "No",
    "feedback.whathappened": "What happened?",
    "feedback.comment-placeholder": "Describe the issue (optional)...",
    "feedback.submit": "Submit Feedback",
    // Rating
    "rating.title": "Was this diagnosis accurate?",
    "rating.comment-placeholder": "Add a comment (optional)...",
    "rating.submit": "Submit Rating",
    // Analysis History
    "history.title": "Analysis History",
    "history.search": "Search analyses...",
    "history.filter-crop": "Filter by crop",
    "history.filter-disease": "Filter by disease",
    "history.sort": "Newest first",
    "history.status.solved": "Solved",
    "history.status.in_progress": "In Progress",
    "history.status.untreated": "Untreated",
    // Farming Guide
    "guide.title": "Farming Guide",
    "guide.search": "Search crops...",
    "guide.planting": "Planting Guide",
    "guide.fertilizer": "Fertilizer Guide",
    "guide.irrigation": "Irrigation",
    "guide.diseases": "Diseases",
    "guide.pests": "Pests",
    "guide.harvesting": "Harvesting",
    "guide.storage": "Storage",
    "guide.best-practices": "Best Practices",
    // Notifications
    "notif.email": "Email",
    "notif.sms": "SMS",
    "notif.in-app": "In-App Notifications",
    "notif.disease-alerts": "Disease Alerts",
    "notif.treatment-reminders": "Treatment Reminders",
    "notif.weekly-tips": "Weekly Tips",
    "notif.weather-alerts": "Weather Alerts",
    "notif.sensor-alerts": "Sensor Alerts",
    "notif.system-announcements": "System Announcements",
    // General
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    search: "Search",
    loading: "Loading...",
    error: "An error occurred",
    "no-data": "No data available",

    "My Farm": "My Farm",
    "Overview": "Overview",
    "My Devices": "My Devices",
    "Buy Hardware": "Buy Hardware",
    "My Orders": "My Orders",
    "Crop Diagnosis": "Crop Diagnosis",
    "Seed Quality": "Seed Quality",
    "Disease Forecast": "Disease Forecast",
    "Analysis History": "Analysis History",
    "Farming Guides": "Farming Guides",
    "AI Assistant": "AI Assistant",
    "Command Center": "Command Center",
    "Knowledge Centre": "Knowledge Centre",
    "Field Officer": "Field Officer",
    "My Tasks": "My Tasks",
    "Farmers Directory": "Farmers Directory",
    "Manage Knowledge": "Manage Knowledge",
    "Platform": "Platform",
    "Dashboard": "Dashboard",
    "Farmers": "Farmers",
    "Deployments": "Deployments",
    "All Devices": "All Devices",
    "Hardware Inventory": "Hardware Inventory",
    "Maintenance Logs": "Maintenance Logs",
    "Alerts": "Alerts",
    "Analytics": "Analytics",
    "Administration": "Administration",
    "Staff": "Staff",
    "Achievements": "Achievements",
    "System Audit Logs": "System Audit Logs",
    "Admin Actions": "Admin Actions",
  },
  ha: {
    dashboard: "Allon Kula",
    farmers: "Manoma",
    devices: "Na'urorin",
    "crop-diagnosis": "Ganowa Cututtukan Amfanin Gona",
    "ai-assistant": "Mataimakin AI",
    alerts: "Fadakarwa",
    analytics: "Bayani na Kididdiga",
    settings: "Saiti",
    logout: "Fita",
    "analysis-history": "Tarihin Bincike",
    "farming-guide": "Jagoran Noma",
    "admin-audit-logs": "Rikodin Ayyuka",
    "diagnosis.disease": "Cuta",
    "diagnosis.confidence": "Tabbatarwa",
    "diagnosis.severity": "Tsanani",
    "diagnosis.recommended-action": "Shawarar Aiki",
    "diagnosis.prevention": "Hanyoyin Rigakafi",
    "diagnosis.recovery": "Lokacin Murmurewa",
    "diagnosis.severity.low": "Ƙanƙanta",
    "diagnosis.severity.medium": "Matsakaici",
    "diagnosis.severity.high": "Tsanani",
    "diagnosis.severity.critical": "Mai Haɗari",
    "feedback.title": "Shin shawarar ta warware matsalarku?",
    "feedback.yes": "Eh",
    "feedback.no": "A'a",
    "feedback.whathappened": "Mene ne ya faru?",
    "feedback.comment-placeholder": "Bayyana matsalar (zaɓi ne)...",
    "feedback.submit": "Aika Martani",
    "rating.title": "Shin ganewar cuta ta kasance daidai?",
    "rating.comment-placeholder": "Ƙara sharhi (zaɓi ne)...",
    "rating.submit": "Aika Maki",
    "history.title": "Tarihin Bincike",
    "history.search": "Nemo bincike...",
    "history.filter-crop": "Tace ta amfanin gona",
    "history.filter-disease": "Tace ta cuta",
    "history.sort": "Sabon farko",
    "history.status.solved": "An Warware",
    "history.status.in_progress": "Yana ci gaba",
    "history.status.untreated": "Ba a Magance ba",
    "guide.title": "Jagoran Noma",
    "guide.search": "Nemo amfanin gona...",
    "guide.planting": "Jagoran Shuka",
    "guide.fertilizer": "Jagoran Takin Zamani",
    "guide.irrigation": "Baiwa",
    "guide.diseases": "Cututtuka",
    "guide.pests": "Ƙwaro",
    "guide.harvesting": "Girbi",
    "guide.storage": "Adanawa",
    "guide.best-practices": "Mafi Kyawun Ayyuka",
    "notif.email": "Imel",
    "notif.sms": "SMS",
    "notif.in-app": "Sanarwa a cikin Manhajar",
    "notif.disease-alerts": "Faɗakarwar Cuta",
    "notif.treatment-reminders": "Tunatarwar Magani",
    "notif.weekly-tips": "Shawarwari na Mako-mako",
    "notif.weather-alerts": "Faɗakarwar Yanayi",
    "notif.sensor-alerts": "Faɗakarwar Na'ura",
    "notif.system-announcements": "Sanarwar Tsarin",
    save: "Ajiye",
    cancel: "Soke",
    delete: "Goge",
    edit: "Gyara",
    search: "Nema",
    loading: "Ana ɗaukewa...",
    error: "An sami kuskure",
    "no-data": "Babu bayanan da ake da su",

    "My Farm": "Gona ta",
    "Overview": "Dubawa",
    "My Devices": "Na'urorina",
    "Buy Hardware": "Sayi Na'ura",
    "My Orders": "Odojina",
    "Crop Diagnosis": "Binciken Amfanin Gona",
    "Seed Quality": "Ingancin Iri",
    "Disease Forecast": "Hasashen Cuta",
    "Analysis History": "Tarihin Bincike",
    "Farming Guides": "Jagoran Noma",
    "AI Assistant": "Mataimakin AI",
    "Command Center": "Cibiyar Kula",
    "Knowledge Centre": "Cibiyar Ilimi",
    "Field Officer": "Jami'in Fage",
    "My Tasks": "Ayyukana",
    "Farmers Directory": "Kundin Manoma",
    "Manage Knowledge": "Sarrafa Ilimi",
    "Platform": "Dandalin",
    "Dashboard": "Allon Kula",
    "Farmers": "Manoma",
    "Deployments": "Turawa",
    "All Devices": "Dukkan Na'urori",
    "Hardware Inventory": "Kayan Na'ura",
    "Maintenance Logs": "Rikodin Gyara",
    "Alerts": "Fadakarwa",
    "Analytics": "Kididdiga",
    "Administration": "Gudanarwa",
    "Staff": "Ma'aikata",
    "Achievements": "Nasara",
    "System Audit Logs": "Rikodin Ayyukan Tsarin",
    "Admin Actions": "Ayyukan Gudanarwa",
  },
  fr: {
    dashboard: "Tableau de bord",
    farmers: "Agriculteurs",
    devices: "Appareils",
    "crop-diagnosis": "Diagnostic des cultures",
    "ai-assistant": "Assistant IA",
    alerts: "Alertes",
    analytics: "Analyses",
    settings: "Paramètres",
    logout: "Déconnexion",
    "analysis-history": "Historique des analyses",
    "farming-guide": "Guide agricole",
    "admin-audit-logs": "Journal d'audit",
    "diagnosis.disease": "Maladie",
    "diagnosis.confidence": "Confiance",
    "diagnosis.severity": "Gravité",
    "diagnosis.recommended-action": "Action recommandée",
    "diagnosis.prevention": "Conseils de prévention",
    "diagnosis.recovery": "Temps de rétablissement",
    "diagnosis.severity.low": "Faible",
    "diagnosis.severity.medium": "Moyen",
    "diagnosis.severity.high": "Élevé",
    "diagnosis.severity.critical": "Critique",
    "feedback.title": "Cette recommandation a-t-elle résolu votre problème?",
    "feedback.yes": "Oui",
    "feedback.no": "Non",
    "feedback.whathappened": "Que s'est-il passé?",
    "feedback.comment-placeholder": "Décrivez le problème (optionnel)...",
    "feedback.submit": "Soumettre le retour",
    "rating.title": "Ce diagnostic était-il précis?",
    "rating.comment-placeholder": "Ajouter un commentaire (optionnel)...",
    "rating.submit": "Soumettre la note",
    "history.title": "Historique des analyses",
    "history.search": "Rechercher des analyses...",
    "history.filter-crop": "Filtrer par culture",
    "history.filter-disease": "Filtrer par maladie",
    "history.sort": "Les plus récents",
    "history.status.solved": "Résolu",
    "history.status.in_progress": "En cours",
    "history.status.untreated": "Non traité",
    "guide.title": "Guide agricole",
    "guide.search": "Rechercher des cultures...",
    "guide.planting": "Guide de plantation",
    "guide.fertilizer": "Guide des engrais",
    "guide.irrigation": "Irrigation",
    "guide.diseases": "Maladies",
    "guide.pests": "Ravageurs",
    "guide.harvesting": "Récolte",
    "guide.storage": "Stockage",
    "guide.best-practices": "Meilleures pratiques",
    "notif.email": "E-mail",
    "notif.sms": "SMS",
    "notif.in-app": "Notifications in-app",
    "notif.disease-alerts": "Alertes maladies",
    "notif.treatment-reminders": "Rappels de traitement",
    "notif.weekly-tips": "Conseils hebdomadaires",
    "notif.weather-alerts": "Alertes météo",
    "notif.sensor-alerts": "Alertes capteurs",
    "notif.system-announcements": "Annonces système",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    search: "Rechercher",
    loading: "Chargement...",
    error: "Une erreur s'est produite",
    "no-data": "Aucune donnée disponible",

    "My Farm": "Ma Ferme",
    "Overview": "Aperçu",
    "My Devices": "Mes Appareils",
    "Buy Hardware": "Acheter du Matériel",
    "My Orders": "Mes Commandes",
    "Crop Diagnosis": "Diagnostic des Cultures",
    "Seed Quality": "Qualité des Graines",
    "Disease Forecast": "Prévision des Maladies",
    "Analysis History": "Historique des Analyses",
    "Farming Guides": "Guides Agricoles",
    "AI Assistant": "Assistant IA",
    "Command Center": "Centre de Commande",
    "Knowledge Centre": "Centre de Connaissances",
    "Field Officer": "Agent de Terrain",
    "My Tasks": "Mes Tâches",
    "Farmers Directory": "Annuaire des Agriculteurs",
    "Manage Knowledge": "Gérer les Connaissances",
    "Platform": "Plateforme",
    "Dashboard": "Tableau de Bord",
    "Farmers": "Agriculteurs",
    "Deployments": "Déploiements",
    "All Devices": "Tous les Appareils",
    "Hardware Inventory": "Inventaire du Matériel",
    "Maintenance Logs": "Journaux de Maintenance",
    "Alerts": "Alertes",
    "Analytics": "Analyses",
    "Administration": "Administration",
    "Staff": "Personnel",
    "Achievements": "Réalisations",
    "System Audit Logs": "Journaux d'Audit",
    "Admin Actions": "Actions Administratives",
  },
  ar: {
    dashboard: "لوحة التحكم",
    farmers: "المزارعون",
    devices: "الأجهزة",
    "crop-diagnosis": "تشخيص المحاصيل",
    "ai-assistant": "المساعد الذكي",
    alerts: "التنبيهات",
    analytics: "التحليلات",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    "analysis-history": "تاريخ التحليل",
    "farming-guide": "دليل الزراعة",
    "admin-audit-logs": "سجلات المراجعة",
    "diagnosis.disease": "المرض",
    "diagnosis.confidence": "الثقة",
    "diagnosis.severity": "الشدة",
    "diagnosis.recommended-action": "الإجراء الموصى به",
    "diagnosis.prevention": "نصائح الوقاية",
    "diagnosis.recovery": "وقت التعافي المتوقع",
    "diagnosis.severity.low": "منخفض",
    "diagnosis.severity.medium": "متوسط",
    "diagnosis.severity.high": "مرتفع",
    "diagnosis.severity.critical": "حرج",
    "feedback.title": "هل حلّت هذه التوصية مشكلتك؟",
    "feedback.yes": "نعم",
    "feedback.no": "لا",
    "feedback.whathappened": "ماذا حدث؟",
    "feedback.comment-placeholder": "صف المشكلة (اختياري)...",
    "feedback.submit": "إرسال التغذية الراجعة",
    "rating.title": "هل كان هذا التشخيص دقيقاً؟",
    "rating.comment-placeholder": "أضف تعليقاً (اختياري)...",
    "rating.submit": "إرسال التقييم",
    "history.title": "تاريخ التحليل",
    "history.search": "البحث في التحليلات...",
    "history.filter-crop": "تصفية حسب المحصول",
    "history.filter-disease": "تصفية حسب المرض",
    "history.sort": "الأحدث أولاً",
    "history.status.solved": "محلول",
    "history.status.in_progress": "قيد المعالجة",
    "history.status.untreated": "غير معالج",
    "guide.title": "دليل الزراعة",
    "guide.search": "البحث في المحاصيل...",
    "guide.planting": "دليل الزراعة",
    "guide.fertilizer": "دليل الأسمدة",
    "guide.irrigation": "الري",
    "guide.diseases": "الأمراض",
    "guide.pests": "الآفات",
    "guide.harvesting": "الحصاد",
    "guide.storage": "التخزين",
    "guide.best-practices": "أفضل الممارسات",
    "notif.email": "البريد الإلكتروني",
    "notif.sms": "رسالة نصية",
    "notif.in-app": "الإشعارات داخل التطبيق",
    "notif.disease-alerts": "تنبيهات الأمراض",
    "notif.treatment-reminders": "تذكيرات العلاج",
    "notif.weekly-tips": "النصائح الأسبوعية",
    "notif.weather-alerts": "تنبيهات الطقس",
    "notif.sensor-alerts": "تنبيهات المستشعر",
    "notif.system-announcements": "إعلانات النظام",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    search: "بحث",
    loading: "جار التحميل...",
    error: "حدث خطأ",
    "no-data": "لا توجد بيانات متاحة",

    "My Farm": "مزرعتي",
    "Overview": "نظرة عامة",
    "My Devices": "أجهزتي",
    "Buy Hardware": "شراء الأجهزة",
    "My Orders": "طلباتي",
    "Crop Diagnosis": "تشخيص المحاصيل",
    "Seed Quality": "جودة البذور",
    "Disease Forecast": "توقع الأمراض",
    "Analysis History": "تاريخ التحليل",
    "Farming Guides": "أدلة الزراعة",
    "AI Assistant": "المساعد الذكي",
    "Command Center": "مركز القيادة",
    "Knowledge Centre": "مركز المعرفة",
    "Field Officer": "موظف ميداني",
    "My Tasks": "مهامي",
    "Farmers Directory": "دليل المزارعين",
    "Manage Knowledge": "إدارة المعرفة",
    "Platform": "المنصة",
    "Dashboard": "لوحة القيادة",
    "Farmers": "المزارعون",
    "Deployments": "الانتشارات",
    "All Devices": "جميع الأجهزة",
    "Hardware Inventory": "جرد الأجهزة",
    "Maintenance Logs": "سجلات الصيانة",
    "Alerts": "تنبيهات",
    "Analytics": "التحليلات",
    "Administration": "الإدارة",
    "Staff": "الموظفون",
    "Achievements": "الإنجازات",
    "System Audit Logs": "سجلات النظام",
    "Admin Actions": "إجراءات الإدارة",
  },
  sw: {
    dashboard: "Dashibodi",
    farmers: "Wakulima",
    devices: "Vifaa",
    "crop-diagnosis": "Utambuzi wa Mazao",
    "ai-assistant": "Msaidizi wa AI",
    alerts: "Tahadhari",
    analytics: "Uchambuzi",
    settings: "Mipangilio",
    logout: "Toka",
    "analysis-history": "Historia ya Uchambuzi",
    "farming-guide": "Mwongozo wa Kilimo",
    "admin-audit-logs": "Kumbukumbu za Ukaguzi",
    "diagnosis.disease": "Ugonjwa",
    "diagnosis.confidence": "Uhakika",
    "diagnosis.severity": "Ukali",
    "diagnosis.recommended-action": "Hatua Inayopendekezwa",
    "diagnosis.prevention": "Vidokezo vya Kuzuia",
    "diagnosis.recovery": "Wakati wa Kupona",
    "diagnosis.severity.low": "Chini",
    "diagnosis.severity.medium": "Wastani",
    "diagnosis.severity.high": "Juu",
    "diagnosis.severity.critical": "Hatari",
    "feedback.title": "Je, pendekezo hili lilisuluhisha tatizo lako?",
    "feedback.yes": "Ndio",
    "feedback.no": "Hapana",
    "feedback.whathappened": "Nini kilitokea?",
    "feedback.comment-placeholder": "Eleza tatizo (si lazima)...",
    "feedback.submit": "Wasilisha Maoni",
    "rating.title": "Je, utambuzi huu ulikuwa sahihi?",
    "rating.comment-placeholder": "Ongeza maoni (si lazima)...",
    "rating.submit": "Wasilisha Kiwango",
    "history.title": "Historia ya Uchambuzi",
    "history.search": "Tafuta uchambuzi...",
    "history.filter-crop": "Chuja kwa zao",
    "history.filter-disease": "Chuja kwa ugonjwa",
    "history.sort": "Mpya kwanza",
    "history.status.solved": "Suluhishwa",
    "history.status.in_progress": "Inaendelea",
    "history.status.untreated": "Haijatumiwa dawa",
    "guide.title": "Mwongozo wa Kilimo",
    "guide.search": "Tafuta mazao...",
    "guide.planting": "Mwongozo wa Kupanda",
    "guide.fertilizer": "Mwongozo wa Mbolea",
    "guide.irrigation": "Umwagiliaji",
    "guide.diseases": "Magonjwa",
    "guide.pests": "Wadudu",
    "guide.harvesting": "Mavuno",
    "guide.storage": "Uhifadhi",
    "guide.best-practices": "Mbinu Bora",
    "notif.email": "Barua pepe",
    "notif.sms": "SMS",
    "notif.in-app": "Arifa za ndani ya programu",
    "notif.disease-alerts": "Tahadhari za Magonjwa",
    "notif.treatment-reminders": "Vikumbusho vya Matibabu",
    "notif.weekly-tips": "Vidokezo vya Kila Wiki",
    "notif.weather-alerts": "Tahadhari za Hali ya Hewa",
    "notif.sensor-alerts": "Tahadhari za Sensorer",
    "notif.system-announcements": "Matangazo ya Mfumo",
    save: "Hifadhi",
    cancel: "Ghairi",
    delete: "Futa",
    edit: "Hariri",
    search: "Tafuta",
    loading: "Inapakia...",
    error: "Hitilafu imetokea",
    "no-data": "Hakuna data inayopatikana",

    "My Farm": "Shamba Langu",
    "Overview": "Muhtasari",
    "My Devices": "Vifaa Vyangu",
    "Buy Hardware": "Nunua Vifaa",
    "My Orders": "Agizo Langu",
    "Crop Diagnosis": "Utambuzi wa Mazao",
    "Seed Quality": "Ubora wa Mbegu",
    "Disease Forecast": "Utabiri wa Magonjwa",
    "Analysis History": "Historia ya Uchambuzi",
    "Farming Guides": "Miongozo ya Kilimo",
    "AI Assistant": "Msaidizi wa AI",
    "Command Center": "Kituo cha Amri",
    "Knowledge Centre": "Kituo cha Maarifa",
    "Field Officer": "Afisa wa Nyanjani",
    "My Tasks": "Kazi Zangu",
    "Farmers Directory": "Orodha ya Wakulima",
    "Manage Knowledge": "Simamia Maarifa",
    "Platform": "Jukwaa",
    "Dashboard": "Dashibodi",
    "Farmers": "Wakulima",
    "Deployments": "Kusambazwa",
    "All Devices": "Vifaa Vyote",
    "Hardware Inventory": "Orodha ya Vifaa",
    "Maintenance Logs": "Kumbukumbu za Matengenezo",
    "Alerts": "Tahadhari",
    "Analytics": "Uchambuzi",
    "Administration": "Utawala",
    "Staff": "Wafanyakazi",
    "Achievements": "Mafanikio",
    "System Audit Logs": "Kumbukumbu za Ukaguzi wa Mfumo",
    "Admin Actions": "Vitendo vya Msimamizi",
  },
};

interface LanguageContextValue {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

const STORAGE_KEY = "agroguard_lang";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return (stored as SupportedLanguage) ?? "en";
  });

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
    document.cookie = `googtrans=/en/${lang}; path=/`;
    document.cookie = `googtrans=/en/${lang}; path=/; domain=${window.location.hostname}`;
    window.location.reload();
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    
    // Sync Google Translate cookie if it doesn't match
    const expectedCookie = `/en/${language}`;
    if (!document.cookie.includes(`googtrans=${expectedCookie}`)) {
      document.cookie = `googtrans=${expectedCookie}; path=/`;
      document.cookie = `googtrans=${expectedCookie}; path=/; domain=${window.location.hostname}`;
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations["en"]?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
