/**
 * Alerts table schema
 * Farm alerts generated by the platform or AI engine.
 * Alerts can be sent via WhatsApp to farmers.
 */
import { pgTable, text, serial, timestamp, boolean, integer } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const alertsTable = pgTable("alerts", {
  id: serial("id").primaryKey(),
  /** FK to farmers.id — may be null for system-wide alerts */
  farmerId: integer("farmer_id"),
  /** FK to devices.id — may be null */
  deviceId: integer("device_id"),
  /**
   * Alert category:
   * soil_moisture | temperature | humidity | pest | disease | irrigation | general
   */
  type: text("type").notNull(),
  /** low | medium | high | critical */
  severity: text("severity").notNull().default("medium"),
  message: text("message").notNull(),
  /** active | resolved | dismissed */
  status: text("status").notNull().default("active"),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  /** Whether the WhatsApp notification was sent to the farmer */
  whatsappSent: boolean("whatsapp_sent").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertAlertSchema = createInsertSchema(alertsTable).omit({
  id: true,
  createdAt: true,
});
export type InsertAlert = z.infer<typeof insertAlertSchema>;
export type Alert = typeof alertsTable.$inferSelect;
